### ISSUE TITLE
Allow files to be received in the background

### ISSUE THREAD

**Issue by FeBe95** [thura10/airwave#6]
It would be nice if files could be received without actively clicking on "receive files". Maybe add it as a setting and/or add a whitelist for MAC addresses of "known" devices to prevent of this features misuse. When a file is received airwave could send a Windows toast message.

**Comment by thura10** [comment]
That's an interesting idea. I think it might also be a big security flaw. For the time, I'm trying to work on a prompt first so that you have to accept the files first. Then I'll try to do this. 

A whitelist might not work at all. It's not possible to get a MAC address from a connection. I have an idea of some other way you can implement this tho.

Do you think the amount of RAM consumption is acceptable for an always-on receiver as there would be a server running at all times.

**Comment by thura10** [comment]
This is now done. You can send files so long as you know the IP address. I have not added an option to disable always-on since it only uses 5 additional megabytes of ram.
You get a toast notification to accept the files from which device. You can also reject it and you will get a notification on the phone to say it was declined.
You have to download new shortcuts, which I have not added yet.
A whitelist is also not made since you can accept or reject every transfer.
https://github.com/thura10/airwave/commit/2fa9604f48851dfd8446d8133d3d98a89238a9be
