### ISSUE TITLE
Option to "trust iphone" on PC

### ISSUE THREAD

**Issue by HexCodeFFF** [thura10/airwave#9]
The receiving without having the dialogue open is actually really neat and a cool addition, but you have to click accept every time. Can we have an option to "trust" an iphone to always accept files from it?

**Comment by thura10** [comment]
Okay this is a great idea. But since there is no way to get a unique identifier from shortcuts, I'm gonna use a 'secret key'. You can input a key in settings and in shortcuts. If they match, you won't be asked for a prompt. Otherwise, you'll be asked for a prompt. That sounds like a good way to implement this.

**Comment by thura10** [comment]
ok yes. It is now done. You have to get the new shortcut and the new release of airwave as well. Enter the same secret key and you will not be prompted.

https://github.com/thura10/airwave/commit/76aea9b7b8d4e2e0de3c61bc0ae0b7029c8cab6b
